Enabled: true #Enable/Disable the itemglow.
flashy-interval: 5 #The interval of the flash effect in ticks.
rainbow-interval: 5 #The interval of the rainbow effect in ticks.
Items:
  example-item: #This would make that any item without a custom name will glow WHITE
    item-material: "any"
    item-name: "any"
    item-lore:
    glow-color: "WHITE"
    low-priority: true
  example-item2: #This would make that any DRAGON EGG item will glow DARK PURPLE
    item-material: "DRAGON_EGG"
    item-name: "any"
    item-lore:
    glow-color: "DARK_PURPLE"
  example-item3: #This would make that any item with the name "Enchanted Wheat" in LIME color will glow RED
    item-material: "any"
    item-name: "&aEnchanted Wheat"
    item-lore:
    glow-color: "RED"
  example-item4: #This would make that any item with the name "Enchanted Wheat" in LIME color and "Material" lore line will glow RED
    item-material: "any"
    item-name: "&aEnchanted Wheat"
    item-lore: "&f&lCOMMON"
    glow-color: "RED"
  example-item5: #This would make that any item with the name "Enchanted Wheat" in LIME color and "Material" lore line will glow RED
    item-material: "DIAMOND_SWORD"
    item-name: "any"
    item-lore: "any"
    glow-color: "RAINBOW"
  example-item6: #This would make that any item with the name "Enchanted Wheat" in LIME color and "Material" lore line will glow RED
    item-material: "GRASS_BLOCK"
    item-name: "any"
    item-lore: "any"
    glow-color: "FLASHY-RED"